### ISSUE TITLE
Ultimate Web development framework/workflow ... 

### ISSUE THREAD

**Issue by raoofha** [bevry-archive/ideashare#11]
hi again . 

it's not actually my idea I just gather some cool stuff around the Internet and add my understanding of how to develop a website/app to it.

I wanted to implement this idea myself and since I'm probebly not going to do that and you are so nice and responsive people and I'm not having any blog yet, I said to myself to put it here.

[Sailsjs](http://sailsjs.org) + [docpad](http://docpad.org) ( thanks to you ) + [reactive-coffee](http://yang.github.io/reactive-coffee) + [semantic-ui](http://semantic-ui.com/) + [pouchdb](http://pouchdb.com) + [hoodie](http://hood.ie) ( dream coding ) I think is the Ultimate Web development solution with some tweak

I think the Ultimate Web framework must obey this rules :

1- Dream Coded 
- every api, command line tools, workflow ... shoud design in the way that is so easy to use and so comprehensive for more info see [dream code](http://nobackend.org/dreamcode.html)

2- DRY ( don't repeat yourself )
- if we code just write one template and one model for our static and dynamic site it would be awesome 
- auto database sync 
- ...

3- Modular Declarative and Semantic UI
- reactive-coffee done very nice job on UI and template design with their nice DSL ( domain specific langugage ) in coffeescript. and I think others are doing it wrong 

4- Reactive
- reactive programming make life so much easier

5- RESTful 
- REST is awesome

6- Realtime

...

what is missing ?

1- Transcompiler to compile reactive-coffee DSL to html
-  Single Template Lang for both client and server side rendering 
  - Angular team I think are doing something about it but it's not in coffeescript 

2- Docpad plugin for reactive-coffee DSL

3- merge Docpad static generators with Sailsjs

4- UI library in reactive-coffee
- I think we could easily wrap UI around jqueryui

5- ...

sorry for any spelling error I recently move to firefox and don't know why spell checker don't work. 
and of course sorry for my poor English I made it berif, if you didn't get it let me know 

thanks for reading :)

**Comment by raoofha** [comment]
oh really?!! not even a "WTF cave boy, Don't you know about RoR?"

**Comment by balupton** [comment]
Seems like ther eis some crossover here with https://github.com/docpad/docpad/issues/880
